config/routes.rb
Locationview::Application.routes.draw do
  resources :location_targets

  resources :customers

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"  # The priority is based upon order of creation: first created -> highest priority.
  get "map" => "pages#map"

end

app/models/customer.rb
require 'securerandom'
class Customer < ActiveRecord::Base
	after_initialize :defaults

	def defaults
			self.authtoken = SecureRandom.hex(8) if self.authtoken.nil?
	end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [] # for all pages
  before_action :admin_access, except: [] # for all pages
  
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def admin_access
      if (current_user.email != "write2krishna@gmail.com")
        redirect_to root_path, notice: "Not authorized" 
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:mobilenumber, :authtoken, :locationtarget, :pricepoint)
    end
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mobilenumber %><br>
    <%= f.text_field :mobilenumber %>
  </div>
  <div class="field">
    <%= f.label :authtoken %><br>
    <%= f.text_field :authtoken %>
  </div>
  <div class="field">
    <%= f.label :locationtarget %><br>
    <%= f.text_field :locationtarget %>
  </div>
  <div class="field">
    <%= f.label :pricepoint %><br>
    <%= f.text_field :pricepoint %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>Mobilenumber</th>
      <th>Authtoken</th>
      <th>Locationtarget</th>
      <th>Pricepoint</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.mobilenumber %></td>
        <td><%= customer.authtoken %></td>
        <td><%= customer.locationtarget %></td>
        <td><%= customer.pricepoint %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mobilenumber:</strong>
  <%= @customer.mobilenumber %>
</p>

<p>
  <strong>Authtoken:</strong>
  <%= @customer.authtoken %>
</p>

<p>
  <strong>Locationtarget:</strong>
  <%= @customer.locationtarget %>
</p>

<p>
  <strong>Pricepoint:</strong>
  <%= @customer.pricepoint %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>