config/routes.rb
Locationview::Application.routes.draw do
  resources :location_targets

  resources :customers

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"  # The priority is based upon order of creation: first created -> highest priority.
  get "map" => "pages#map"

end

app/models/location_target.rb
class LocationTarget < ActiveRecord::Base
	#geocoded_by :address
  #after_validation :geocode
end

app/controllers/location_targets_controller.rb
class LocationTargetsController < ApplicationController
  before_action :set_location_target, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [] # for all pages
  before_action :admin_access, except: [] # for all pages

  # GET /location_targets
  # GET /location_targets.json
  def index
    @location_targets = LocationTarget.all
  end

  # GET /location_targets/1
  # GET /location_targets/1.json
  def show
  end

  # GET /location_targets/new
  def new
    @location_target = LocationTarget.new
  end

  # GET /location_targets/1/edit
  def edit
  end

  # POST /location_targets
  # POST /location_targets.json
  def create
    @location_target = LocationTarget.new(location_target_params)

    respond_to do |format|
      if @location_target.save
        format.html { redirect_to @location_target, notice: 'Location target was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location_target }
      else
        format.html { render action: 'new' }
        format.json { render json: @location_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /location_targets/1
  # PATCH/PUT /location_targets/1.json
  def update
    respond_to do |format|
      if @location_target.update(location_target_params)
        format.html { redirect_to @location_target, notice: 'Location target was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /location_targets/1
  # DELETE /location_targets/1.json
  def destroy
    @location_target.destroy
    respond_to do |format|
      format.html { redirect_to location_targets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location_target
      @location_target = LocationTarget.find(params[:id])
    end

    def admin_access
      if (current_user.email != "write2krishna@gmail.com")
        redirect_to root_path, notice: "Not authorized" 
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_target_params
      params.require(:location_target).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/helpers/location_targets_helper.rb
module LocationTargetsHelper
end

app/views/location_targets/_form.html.erb
<%= form_for(@location_target) do |f| %>
  <% if @location_target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location_target.errors.count, "error") %> prohibited this location_target from being saved:</h2>

      <ul>
      <% @location_target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/location_targets/edit.html.erb
<h1>Editing location_target</h1>

<%= render 'form' %>

<%= link_to 'Show', @location_target %> |
<%= link_to 'Back', location_targets_path %>

app/views/location_targets/index.html.erb
<h1>Listing location_targets</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Description</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @location_targets.each do |location_target| %>
      <tr>
        <td><%= location_target.latitude %></td>
        <td><%= location_target.longitude %></td>
        <td><%= location_target.address %></td>
        <td><%= location_target.description %></td>
        <td><%= location_target.title %></td>
        <td><%= link_to 'Show', location_target %></td>
        <td><%= link_to 'Edit', edit_location_target_path(location_target) %></td>
        <td><%= link_to 'Destroy', location_target, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location target', new_location_target_path %>

app/views/location_targets/new.html.erb
<h1>New location_target</h1>

<%= render 'form' %>

<%= link_to 'Back', location_targets_path %>

app/views/location_targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @location_target.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location_target.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location_target.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location_target.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @location_target.title %>
</p>

<%= link_to 'Edit', edit_location_target_path(@location_target) %> |
<%= link_to 'Back', location_targets_path %>